name: My First WorkFlow
on: push
jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Checkout Action
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Running Commands
        run: ls -al && touch a.com && ls
        