name: Job Context Information
on: push
jobs:
  JobContextInformation:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Variables and Values
        run: |
         echo "Variable job.container ${{job.container}}"
         echo "Variable job.status ${{job.status}}"
         echo "Hello"