name : Job Output With Needs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.step1.outputs.name }}
    steps:
      - id: step1
        run: echo "name=my-app" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Deploying ${{ needs.build.outputs.artifact_name }}"
