name: My First WorkFlow
on: push
jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Action Checkout
        uses: actions/checkout@v4
      - name: Checking Node and NPM
        run: node -v && npm -v
        